name: 'Setup Java and Gradle'
description: 'Sets up Java, gradle, and API secrets for use in actual tasks'

inputs:
  GOOGLE_SERVICES_JSON:
    description: 'Base64 encoded google-services.json from secrets'
    required: true
  GOOGLE_CLIENT_ID:
    description: 'GOOGLE_CLIENT_ID from secrets'
    required: true

runs:
  using: "composite"
  steps:
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Create Google Services JSON File
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json
      shell: bash
    - name: Create keys.properties
      env:
        GOOGLE_CLIENT_ID: ${{ inputs.GOOGLE_CLIENT_ID }}
      run: echo "GOOGLE_CLIENT_ID=\"$GOOGLE_CLIENT_ID\"" > keys.properties
      shell: bash
